import type { Profile, Like, Match } from '../types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    firstName: 'נועה',
    lastName: 'כהן',
    age: 26,
    bio: 'אוהבת טיולים, קפה, וכלבים. מחפשת מישהו אמיתי.',
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop',
    ],
    prompts: [
      { id: 'p1', prompt: 'עובדה מפתיעה עליי', answer: 'דוברת 4 שפות ועדיין לא מצליחה להזמין פיצה בטלפון' },
      { id: 'p2', prompt: 'בדרך כלל ביום שבת', answer: 'מטיילת בשוק הכרמל עם קפה ביד' },
    ],
    gender: 'נקבה',
    location: 'תל אביב',
    height: '168 ס"מ',
    isAvailable: true,
    availabilityExpiresAt: new Date(Date.now() + 45 * 60 * 1000),
    meetCute: { activity: 'coffee', mindset: 'real', availabilityVibe: 'chat_first' },
    flowAnswers: {
      trackId: 1,
      trackName: 'הקלאסי והישיר',
      trackEmoji: '🎯',
      trackColor: 'pink',
      step1Question: 'אם קופצים עכשיו למשהו, זה יהיה...',
      step1Answer: 'קפה של אמצע היום ☕',
      step2Question: 'מה הסטייט אוף מיינד שלך לאחרונה?',
      step2Answer: 'מחפש/ת את הדבר האמיתי 🎯',
      icebreaker: 'פיצה עם מלא אננס, תשפטו אותי 🍕',
    },
  },
  {
    id: '2',
    firstName: 'עידו',
    lastName: 'לוי',
    age: 29,
    bio: 'מתכנת ביום, שף חובב בלילה. מחפש את הקפה הכי טוב בתל אביב.',
    photos: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=500&fit=crop',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    ],
    prompts: [
      { id: 'p3', prompt: 'הדבר הכי מוזר שאני עושה', answer: 'מדרג כל בית קפה לפי זמן המתנה לאספרסו' },
    ],
    gender: 'זכר',
    location: 'תל אביב',
    height: '182 ס"מ',
    isAvailable: true,
    availabilityExpiresAt: new Date(Date.now() + 90 * 60 * 1000),
    meetCute: { activity: 'drink', mindset: 'flow', availabilityVibe: 'ready_now' },
    flowAnswers: {
      trackId: 2,
      trackName: 'הזורם והשובב',
      trackEmoji: '🌊',
      trackColor: 'violet',
      step1Question: 'איך נראה הערב החופשי המושלם שלך?',
      step1Answer: 'בירה עם חברים קרובים 🍻',
      step2Question: 'מה עושה לך את זה בשיחה טובה?',
      step2Answer: 'עקיצות וצחוקים 😂',
      icebreaker: 'אם היית חייב לאכול רק דבר אחד שנה שלמה, מה היה?',
    },
  },
  {
    id: '3',
    firstName: 'מאיה',
    lastName: 'ברק',
    age: 24,
    bio: 'סטודנטית לאמנות. אוהבת מוזיאונים, מוסיקה חיה, ושוקולד מריר.',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=500&fit=crop',
    ],
    prompts: [
      { id: 'p4', prompt: 'הדבר שאני הכי גאה בו', answer: 'ציירתי 365 יום ברצף – גם בימים הגרועים ביותר' },
      { id: 'p5', prompt: 'אני לא אסכים/תסכים על', answer: 'שפיצה עם אננס זה בכלל בסדר' },
    ],
    gender: 'נקבה',
    location: 'ירושלים',
    height: '163 ס"מ',
    isAvailable: true,
    availabilityExpiresAt: new Date(Date.now() + 2 * 60 * 60 * 1000),
    meetCute: { activity: 'drink', mindset: 'friends', availabilityVibe: 'one_hour' },
    flowAnswers: {
      trackId: 3,
      trackName: 'הממוקד',
      trackEmoji: '⚡',
      trackColor: 'amber',
      step1Question: 'איך את/ה מקבל/ת החלטות?',
      step1Answer: 'הכי ספונטני, מעכשיו לעכשיו 🎲',
      step2Question: 'מה מחמם לך את הלב?',
      step2Answer: 'פשוט שמקשיבים לי באמת 👂',
      icebreaker: 'מה הדבר שאסור לך בשום אופן להתחיל לדבר עליו איתי? 🚫',
    },
  },
  {
    id: '4',
    firstName: 'יובל',
    lastName: 'שמש',
    age: 31,
    bio: 'רופא בשנים הראשונות. הסיבה שאני עדיין ער ב-3 לילה היא בד"כ הוספיטל, לא נטפליקס.',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop',
    ],
    prompts: [
      { id: 'p6', prompt: 'אם ארוחה אחרונה', answer: 'פסטה הביתית של סבתא שלי – אין שאלה' },
    ],
    gender: 'זכר',
    location: 'תל אביב',
    height: '179 ס"מ',
    isAvailable: false,
    flowAnswers: {
      trackId: 1,
      trackName: 'הקלאסי והישיר',
      trackEmoji: '🎯',
      trackColor: 'pink',
      step1Question: 'אם קופצים עכשיו למשהו, זה יהיה...',
      step1Answer: 'דרינק של ערב 🍷',
      step2Question: 'מה הסטייט אוף מיינד שלך לאחרונה?',
      step2Answer: 'זורם/ת לראות מה יקרה 🌊',
      icebreaker: 'מהו הגילטי פלז׳ר הכי מביך שלך? שלי הוא ריאליטי על כלים.',
    },
  },
];

export const MOCK_LIKES: Like[] = [
  {
    id: 'l1',
    fromUserId: '1',
    toUserId: 'me',
    profile: MOCK_PROFILES[0],
    answer: MOCK_PROFILES[0].flowAnswers?.icebreaker,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'l2',
    fromUserId: '3',
    toUserId: 'me',
    profile: MOCK_PROFILES[2],
    photoUrl: MOCK_PROFILES[2].photos[0],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'm1',
    userId: '1',
    profile: MOCK_PROFILES[0],
    lastMessage: 'אז מתי נשתה קפה? ☕',
    lastMessageAt: new Date(Date.now() - 10 * 60 * 1000),
    unreadCount: 2,
    meetCute: MOCK_PROFILES[0].meetCute,
  },
  {
    id: 'm2',
    userId: '3',
    profile: MOCK_PROFILES[2],
    lastMessage: 'ראיתי שאתה גם אוהב...',
    lastMessageAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    unreadCount: 0,
    meetCute: MOCK_PROFILES[2].meetCute,
  },
];
